### PR TITLE
Improve flush method to deal with event concurrency & Fix #9

### LINKED ISSUE #9: Validate if event data exists before send events to splunk
captura de tela 2016-08-10 as 16 26 06

### PR DESCRIPTION
**Pull request by nevescode**

### CODE REVIEW

**Comment by brenoc** [comment]
The dist folder should be in .gitignore

**Comment by brenoc** [comment]
LGTM

**Comment by nevescode** [comment]
In this case, as a lib, the dist folder really should be in .gitignore? Look at lodash: https://github.com/lodash/lodash/tree/master/dist 

Why?

**Comment by brenoc** [comment]
Weird. I asked the author about that. You shouldn't need to do that.

**Comment by brenoc** [comment]
@nevescode answer:
https://twitter.com/jdalton/status/766034948637593600

I think we can ignore it. That's not our case.

**Pull request merged**
